# Generated by Django 3.2.18 on 2023-05-28 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DanhMuc', models.TextField(max_length=255)),
                ('DichGia', models.TextField(blank=True)),
                ('GiaNhaNam', models.IntegerField(blank=True)),
                ('GiaBia', models.IntegerField()),
                ('GioiThieuSach', models.TextField(blank=True)),
                ('KichThuoc', models.TextField(max_length=255)),
                ('LinkImage', models.TextField(blank=True)),
                ('MaSanPham', models.CharField(max_length=255)),
                ('NgayPhatHanh', models.DateField(blank=True)),
                ('NhaXuatBan', models.TextField(blank=True, max_length=255)),
                ('SoTrang', models.IntegerField(blank=True)),
                ('TacGia', models.TextField(blank=True)),
                ('Ten', models.TextField()),
            ],
        ),
    ]
