from elasticsearch import Elasticsearch
from elasticsearch.helpers import bulk
HOST = "https://localhost:9200"
ELASTIC_USER = "elastic"
# The password for the 'elastic' user generated by Elasticsearch
ELASTIC_PASSWORD = "-JpPuDA43hk+xp*OYAPq"
# The path of ca certificates
CA_CERTS = "C:/UTEXLMS/Nam3_2022_2023/HK2/TruyTimThongTin/elasticsearch-8.6.2/config/certs/http_ca.crt"

# Điều chỉnh để phù hợp với từng máy
DEV="PHONGPHU"

if DEV=="NGOCPHAT":
    ELASTIC_PASSWORD = "AO_Xpp=erLN89MGxutL7"
    CA_CERTS="P:/Programming/JAVA/Enviroment/elasticsearch-8.6.2-windows-x86_64/elasticsearch-8.6.2/config/certs/http_ca.crt"
elif DEV=="PHONGPHU":
    ELASTIC_PASSWORD = "-JpPuDA43hk+xp*OYAPq"
    CA_CERTS = "C:/UTEXLMS/Nam3_2022_2023/HK2/TruyTimThongTin/elasticsearch-8.6.2/config/certs/http_ca.crt"
elif DEV=="DUCPHAP":
    ELASTIC_PASSWORD = "YNhxANqPGqbMGF3ZzH0c"
    CA_CERTS = "C:/Users/ad/elasticsearch-8.6.2/config/certs/http_ca.crt"
elif DEV=="HONGPHAT":
    ELASTIC_PASSWORD = "FnvOknKJE59pVtzA2_9e"
    CA_CERTS = "C:/elasticsearch/config/certs/http_ca.crt"



# Create the client instance
es = Elasticsearch(
    hosts=HOST,
    ca_certs=CA_CERTS,
    http_auth=(ELASTIC_USER, ELASTIC_PASSWORD),
)

# Define index name of project
index_name = 'finalproject_index'
type_name = "_search"